package nl.tudelft.jpacman.level;

import static sqat.series2.Api.hit;
import nl.tudelft.jpacman.board.Unit;
import nl.tudelft.jpacman.level.CollisionInteractionMap.CollisionHandler;
import nl.tudelft.jpacman.npc.ghost.Ghost;

public class DefaultPlayerInteractionMap implements CollisionMap  {

	private final CollisionMap collisions = defaultCollisions();

	@Override
	public void collide(Unit mover, Unit movedInto)  { hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(646,103,<22,1>,<25,2>)"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(646,103,<22,1>,<25,2>)", "436"); collisions.collide(mover, movedInto); }

	/**
	 * Creates the default collisions Player-Ghost and Player-Pellet.
	 * 
	 * @return The collision map containing collisions for Player-Ghost and
	 *         Player-Pellet.
	 */
	private static CollisionInteractionMap defaultCollisions()  { hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "448"); CollisionInteractionMap collisionMap = new CollisionInteractionMap(); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "449"); collisionMap.onCollision(Player.class, Ghost.class,
				new CollisionHandler<Player, Ghost>() {

					@Override
					public void handleCollision(Player player, Ghost ghost)  { hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "440"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(1172,109,<39,5>,<42,6>)"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "441"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(1172,109,<39,5>,<42,6>)", "437"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "442"); player.setAlive(false); }
				}); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "450"); collisionMap.onCollision(Player.class, Pellet.class,
				new CollisionHandler<Player, Pellet>() {

					@Override
					public void handleCollision(Player player, Pellet pellet)  { hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "443"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(1397,152,<48,5>,<52,6>)"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "444"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(1397,152,<48,5>,<52,6>)", "438"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "445"); pellet.leaveSquare(); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "446"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(1397,152,<48,5>,<52,6>)", "439"); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "447"); player.addPoints(pellet.getValue()); }
				}); hit("|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(514,1071,<18,0>,<56,1>)", "|project://jpacman/src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java|(934,649,<33,1>,<55,2>)", "451"); return collisionMap; }
}
